services:
  devoir-symfony:
    container_name: devoir-symfony
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/var/www/html
      - ./logs:/var/log/apache2/
    ports:
      - "8888:80"

  mysql:
    container_name: mysql-symfony
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: password
